### PR TITLE
tentative fix for stream creation issues

### PR DESCRIPTION
**Pull request by ipelupessy**
this change in the order of the code fixes or at least alleviates #63 for me

to be honest I don't understand why it makes a difference...

### CODE REVIEW

**Comment by rikvanriel** [comment]
Looking around the code some more, I see something interesting.

self.channels in _Stream is a FUNCTION, not a variable that things get assigned to.

That means we should call it as a function when assigning the default channels, I'm currently running with this change to see if it makes a difference:

`--- pulseaudio.py	2020-08-01 17:02:18.934298490 -0400
+++ pulseaudio.py	2020-08-10 09:57:47.992885329 -0400
@@ -579,7 +579,7 @@ class _Microphone(_SoundCard):
         recorder : _Recorder
         """
         if channels is None:
-            channels = self.channels
+            channels = self.channels()
         return _Recorder(self._id, samplerate, channels, blocksize)
 
     def record(self, numframes, samplerate, channels=None, blocksize=None):
`

**Comment by bastibe** [comment]
This... can't be true. Right?

But, thinking about this some more, could it be that the channelmap gets deallocated at some point, which is the real cause of the error? Perhaps saving it to `self._channelmap` instead of `channelmap` could solve the issue (by keeping it alive as long as the stream is alive)? If that helps, the same should probably be true for `samplespec`.

**Comment by rikvanriel** [comment]
I suspect the reason why this worked might be that the python garbage collector and allocator reuse freed objects in some order related to when they were freed and what their addresses are.

Moving the allocation up a little might leave the contents of the freed objects alone a little longer, just long enough they do not get overwritten by the time the new stream has finished getting set up.

**Comment by bastibe** [comment]
@rikvanriel is probably right. At any rate, his be44b6557d68147a5789f7174cf4880f2efe6901 should fix this issue properly.

**Comment by ipelupessy** [comment]
yea, in retrospect.. such change in behaviour after only moving around stuff should trigger a suspicion of a GC issue!

**Comment by rikvanriel** [comment]
But only in retrospect. This is the kind of bug that often requires inspiration by multiple people.

**Pull request closed without merging**
