### PR TITLE
Replace collections.Iterable with collections.abc.Iterable

### PR DESCRIPTION
**Pull request by juligreen**
Closes https://github.com/bastibe/SoundCard/issues/140

### CODE REVIEW

**Comment by bastibe** [comment]
Thank you very much for your contribution!

**Comment by vrslev** [comment]
@bastibe When are you planning on releasing new version that contains this fix? 🙏

**Comment by bastibe** [comment]
I hope I'll find time to do the release this week. Sorry, life is busy.

**Comment by vrslev** [comment]
I understand. Thanks ☺️

**Comment by bastibe** [comment]
I am working on releasing soundfile at the moment. Once that is done, I'll do soundcard.

Terribly sorry that things take time, but I have kids, a job, and only a few hours a week I can dedicate to FOSS. If you want to help out, you can open a pull request with an updated changelog, or open an issue where you run the test suite on all the platforms you have access to. Or better yet, open a pull request that runs the test suite in Github's CI.

**Pull request merged**
