### PR TITLE
Add local pyinstaller hook

### PR DESCRIPTION
**Pull request by Bob-Thomas**
This should remedy #77 by having a local pyinstaller hook according to the new pyinstaller community hooks.

as proposed in https://github.com/pyinstaller/pyinstaller/pull/4834

@Legorooj could you perhaps validate this method as I just grabbed the wgpu example and rolled with it

### CODE REVIEW

**Comment by bastibe** [comment]
Cool, thank you! Thank you very much for putting effort into this!

We'll wait a few days for @Legorooj to answer before we merge.

**Comment by bastibe** [comment]
Thank you very much, gentlemen!

(I wish I knew how to set up CI for SoundCard; but it heavily relies on the audio hardware, and can't really be tested without that. Any tips would be very welcome!)

**Comment by Legorooj** [comment]
@bastibe afraid not... Some sort of emulation would be best, but otherwise I'm not sure. 

Please note that this addition won't have any affect in PyInstaller until next release. (4.0: May-June)

**Comment by bastibe** [comment]
> Please note that this addition won't have any affect in PyInstaller until next release. (4.0: May-June)

I think that's acceptable.

**Pull request merged**
