### PR TITLE
Fixes for issue #15 and Win 8 STA

### PR DESCRIPTION
**Pull request by demberto**
Win 8 STA CoInitialize: https://stackoverflow.com/a/49127178/5541355. _combase definition has been removed and has been replaced everywhere with _ole32. Althought I haven't tested this, it should work perfectly fine. Now this library will be perfectly compatible with all Windows versions from Vista.

### CODE REVIEW

**Comment by bastibe** [comment]
This looks very good, and would finally fix that long-standing incompatibility with Windows 7.

I just checked it on Windows 10, and it seems to work just fine. I can't test it on Windows 7 or 8, as I don't have those available.

**Comment by bastibe** [comment]
Thank you very much for this contribution!

**Comment by Bob-Thomas** [comment]
would this fix the issue of having to initialize com in a new thread as well ? or is that just standard expected behaviour

**Comment by bastibe** [comment]
I have no idea, honestly. I don't know enough about .NET to, sadly. @ghost, do you know more about that?

**Comment by demberto** [comment]
@bastibe you don't need to know .net for this, its all win32 and com. Unfortunately it is a complicated topic and I am just a newbie here, anyways.

**Pull request merged**
