### PR TITLE
Update ffi dlopen for bigsur

### PR DESCRIPTION
**Pull request by 0x0L**
Fixes CoreaAudio dylib open on bigsur

### CODE REVIEW

**Comment by bastibe** [comment]
Does this break older versions of macOS?

**Comment by 0x0L** [comment]
I don't have an easy access to an older version of macos.

Searching for the path on google yields a stackoverflow post from 2014 (https://stackoverflow.com/questions/25714450/os-x-dlopen-cant-find-framework-image-not-found) that references almost the same path (version A instead of Current)

I guess it's ok but it's just a guess

**Comment by bastibe** [comment]
Does anyone else have access to a non-big-sur macOS to test this?

**Comment by 0x0L** [comment]
It looks like it's fixed in an upstream version of python (and also in macos default python)

**Comment by bastibe** [comment]
Is this pull request obsolete, then?

**Comment by 0x0L** [comment]
Yes, I'll close. Thanks

**Pull request closed without merging**
